AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - '**/Rakefile.rb'
    - db/schema.rb
    - 'vendor/**/*'
    - assert_migration.rb

require:
 - rubocop-rake
 - rubocop-rails

Layout/EmptyLines:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Max: 80

Metrics/PerceivedComplexity:
  Max: 30

Metrics/ModuleLength:
  Max: 300

Metrics/ClassLength:
  Max: 1000

Metrics/ParameterLists:
  Max: 10

Metrics/BlockNesting:
  Max: 5

Style/Next:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/ClassVars:
  Enabled: false

Rails/NegateInclude:
  Enabled: false

Security/Eval:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Rails/Output:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false
