aire-de-covoiturages:
  label:
    fr: Aires de covoiturage
  matches:
    - amenity: car_pooling
    - amenity: parking
      carpool: designated
  osm_tags_extra:
    - name
    - description
    - network
    - capacity
    - operator
    - address
    - lit
    - maxstay
    - name
    - description
    - network
    - capacity
    - operator
    - address
    - lit
    - maxstay
gares-sncf:
  label:
    fr: Gare SNCF
  matches:
    - railway: halt
    - railway: station
      operator: SNCF
  osm_tags_extra:
    - address
    - network
    - operator
    - uic_ref
    - description
    - opening_hours
    - phone
    - wheelchair
    - internet_access
    - address
    - network
    - operator
    - uic_ref
    - description
    - opening_hours
    - wheelchair
    - phone
    - internet_access
parking-public:
  label:
    fr: Parking public
  matches:
    - amenity: parking
      access: 'yes'
      parking!: street_side
  osm_tags_extra:
    - address
    - capacity
    - maxstay
    - fee
    - lit
    - opening_hours
    - parking
    - wheelchair
    - maxheight
parking-velo:
  label:
    fr: Parking vélo
  matches:
    - amenity: bicycle_parking
  osm_tags_extra:
    - operator
    - capacity
    - bicycle_parking
    - maxstay
    - fee
    - covered
    - access
    - supervised
    - operator
    - address
    - capacity
    - bicycle_parking
    - covered
    - access
    - supervised
boucherie-charcuterie-osm:
  label:
    fr: Boucheries / Charcuteries
  matches:
    - shop: butcher
  osm_tags_extra:
    - address
    - phone
    - opening_hours
    - drive_through
    - delivery
    - wheelchair
    - butcher
    - address
    - phone
    - contact:phone
    - opening_hours
    - website
    - contact:facebook
    - facebook
    - delivery
    - drive_through
    - wheelchair
    - butcher
boulangerie-patisserie-osm:
  label:
    fr: Boulangeries / Pâtisseries
  matches:
    - shop: bakery
    - shop: pastry
  osm_tags_extra:
    - phone
    - address
    - craft=bakery
    - pastry
    - delivery
    - drive_through
    - opening_hours
    - organic
    - wheelchair
epicerie-osm:
  label:
    fr: Épiceries
  matches:
    - shop: convenience
  osm_tags_extra:
    - address
    - phone
    - opening_hours
    - brand
    - organic
    - delivery
    - drive_through
    - wheelchair
    - description
    - address
    - contact:phone
    - phone
    - opening_hours
    - website
    - contact:facebook
    - facebook
    - brand
    - organic
    - delivery
    - drive_through
    - wheelchair
    - description
points-deau:
  label:
    fr: Point d’eau
  matches:
    - amenity: drinking_water
      access: 'yes'
  osm_tags_extra:
    - man_made
    - bottle
    - access
    - indoor
    - wheelchair
    - man_made
    - bottle
    - access
    - indoor
    - wheelchair
toilettes-publiques:
  label:
    fr: Toilettes Publiques
  matches:
    - amenity: toilets
      access: 'yes'
  osm_tags_extra:
    - access
    - operator
    - fee
    - wheelchair
    - unisex
    - toilets:disposal
    - toilets:handwashing
    - changing_table
    - supervised
    - male
    - female
    - access
    - operator
    - fee
    - wheelchair
    - unisex
    - toilets:disposal
    - toilets:handwashing
    - changing_table
    - supervised
    - male
    - female
points-de-vue:
  label:
    fr: Points de vue
  matches:
    - tourism: viewpoint
  osm_tags_extra:
    - name
    - description
    - wheelchair
    - tower:type
    - name
    - description
    - wheelchair
points-de-tri:
  label:
    fr: Points de tri
  matches:
    - amenity: recycling
      recycling_type: container
  osm_tags_extra:
    - recycling_type
    - operator
    - recycling:glass_bottles=yes
    - recycling:plastic_bottles=yes
    - recycling:beverage_carton=yes
    - recycling:cans=yes
    - recycling:paper=yes
    - recycling:clothes=yes
    - recycling:batteries=yes
    - recycling:waste
    - recycling_type
    - operator
    - recycling:glass_bottles=yes
    - recycling:beverage_carton=yes
    - recycling:cans=yes
    - recycling:paper=yes
    - recycling:clothes=yes
    - recycling:batteries=yes
    - recycling:waste
offices-de-tourisme-osm:
  label:
    fr: Office du tourisme
  matches:
    - information: office
      access!: customers
  osm_tags_extra:
    - phone
    - description
    - address
    - opening_hours
    - wheelchair
    - contact:email
    - contact:website
    - website
    - contact:facebook
    - internet_access
    - contact:phone
    - phone
    - description
    - address
    - opening_hours
    - wheelchair
    - contact:facebook
    - facebook
    - contact:website
    - contact:email
    - email
    - internet_access
mairies:
  label:
    fr: Mairies
  matches:
    - amenity: townhall
  osm_tags_extra:
    - address
    - phone
    - opening_hours
    - wheelchair
    - description
    - website
    - contact:email
    - wheelchair
    - address
    - phone
    - contact:phone
    - opening_hours
    - description
    - website
    - contact:email
    - contact:website
    - facebook
aire-de-recharge-e:
  label:
    fr: Aires de recharge E
  matches:
    - amenity: charging_station
  osm_tags_extra:
    - operator
    - capacity
    - description
    - fee
    - motorcar
    - truck
    - scooter
    - bicycle
    - owner
    - payment:credit_cards
    - operator
    - capacity
    - fee
    - bicycle
    - motorcar
    - scooter
    - owner
    - payment:credit_cards
aires-de-pique-nique:
  label:
    fr: Aire de pique-nique
  matches:
    - tourism: picnic_site
  osm_tags_extra:
    - name
    - description
    - surface
    - covered
    - lit
    - wheelchair
    - name
    - description
    - surface
    - covered
    - lit
    - wheelchair
reparateurs-de-velo:
  label:
    fr: Réparateurs de vélo
  matches:
    - shop: bicycle
      service:bicycle:repair: 'yes'
  osm_tags_extra:
    - address
    - phone
    - website
    - opening_hours
    - service:bicycle:rental
    - service:bicycle:pump
    - service:bicycle:repair
    - service:bicycle:cleaning
    - service:bicycle:retail
    - service:bicycle:diy
    - wheelchair
    - address
    - phone
    - contact:phone
    - opening_hours
    - website
    - facebook
    - contact:facebook
    - email
    - service:bicycle:retail
    - service:bicycle:rental
    - service:bicycle:pump
    - service:bicycle:cleaning
    - service:bicycle:diy
    - wheelchair
loueurs-de-velo-osm:
  label:
    fr: Loueurs de vélo
  matches:
    - shop: bicycle
      service:bicycle:rental: 'yes'
    - shop: sports
      service:bicycle:rental: 'yes'
  osm_tags_extra:
    - phone
    - address
    - website
    - contact:facebook
    - opening_hours
    - address
    - phone
    - contact:phone
    - opening_hours
    - website
    - facebook
    - contact:facebook
    - wheelchair
gares-routieres:
  label:
    fr: Gares routières
  matches:
    - amenity: bus_station
      public_transport: station
  osm_tags_extra:
    - address
    - description
    - phone
    - opening_hours
    - wheelchair
    - operator
    - address
    - description
    - phone
    - contact:phone
    - opening_hours
    - wheelchair
    - operator
arrets-de-bus-saisonniers-plages:
  label:
    fr: Arrêt de bus saisoniers (plages)
  matches:
    - highway: bus_stop
      seasonnal: summer
  osm_tags_extra:
    - wheelchair
    - shelter
    - bench
    - network
    - operator
    - description
    - wheelchair
    - shelter
    - bench
    - network
    - operator
    - description
vente-a-la-ferme:
  label:
    fr: Magasins à la ferme
  matches:
    - shop: farm
  osm_tags_extra:
    - address
    - phone
    - website
    - facebook
    - opening_hours
    - organic
    - produced_on_site
    - produce
    - delivery
    - drive_through
    - description
    - wheelchair
    - address
    - phone
    - contact:phone
    - opening_hours
    - website
    - contact:website
    - facebook
    - contact:facebook
    - email
    - organic
    - produced_on_site
    - produce
    - delivery
    - drive_through
    - description
    - wheelchair
hopitaux:
  label:
    fr: Hôpital
  matches:
    - amenity: hospital
      emergency: 'yes'
  osm_tags_extra:
    - address
    - phone
    - emergency
    - ref:FR:FINESS
    - type:FR:FINESS
    - healthcare:speciality
    - description
    - address
    - phone
    - emergency
    - ref:FR:FINESS
    - type:FR:FINESS
    - healthcare:speciality
    - description
    - website
dab:
  label:
    fr: DAB
  matches:
    - amenity: atm
  osm_tags_extra:
    - description
    - wheelchair
    - operator
    - operator
    - wheelchair
pharmacies:
  label:
    fr: Pharmacies
  matches:
    - amenity: pharmacy
  osm_tags_extra:
    - address
    - phone
    - opening_hours
    - delivery
    - ref:FR:FINESS
    - drive_through
    - ref:FR:FINESS
    - wheelchair
    - address
    - phone
    - contact:phone
    - opening_hours
    - website
    - delivery
    - drive_through
    - wheelchair
postes-de-secours:
  label:
    fr: Poste de plage
  matches:
    - emergency: water_rescue_station
  osm_tags_extra:
    - description
    - operator
    - wheelchair
    - opening_hours
    - address
    - description
    - operator
    - wheelchair
    - opening_hours
station-de-gonflage-velo:
  label:
    fr: Station de gonflage vélo
  matches:
    - service:bicycle:pump: 'yes'
  osm_tags_extra:
    - opening_hours
    - opening_hours
    - fee
    - access
    - description
defibrillateurs:
  label:
    fr: Défibrillateurs
  matches:
    - emergency: defibrillator
  osm_tags_extra:
    - operator
    - address
    - defibrillator:location
    - operator
    - address
    - defibrillator:location
    - indoor
    - description
    - indoor
    - access
    - opening_hours
parcs-et-jardins-avec-visites-osm:
  label:
    fr: Parcs
  matches:
    - leisure: park
  osm_tags_extra:
    - operator
    - description
    - opening_hours
    - wheelchair
    - dog
golfs-osm:
  label:
    fr: Golf
  matches:
    - sport: golf
  osm_tags_extra:
    - address
    - sport
    - operator
    - phone
    - description
    - website
    - operator
    - surface
    - description
    - opening_hours
    - contact:phone
    - website
plages-interieures-littoral-osm:
  label:
    fr: Plages
  matches:
    - natural: beach
  osm_tags_extra:
    - operator
    - wheelchair
    - lit
    - description
    - operator
    - surface
    - lit
    - wheelchair
centres-aquatiques-osm:
  label:
    fr: Piscine
  matches:
    - leisure: swimming_pool
      access: 'yes'
    - leisure: sports_centre
      sport: swimming
  osm_tags_extra:
    - address
    - sport
    - operator
    - phone
    - description
    - website
    - length
    - wheelchair
    - fee
    - description
    - operator
    - sport
    - opening_hours
    - fee
    - length
    - contact:phone
    - wheelchair
aires-de-camping-car-osm:
  label:
    fr: Aires de camping-cars
  matches:
    - tourism: caravan_site
  osm_tags_extra:
    - capacity
    - fee
    - operator
    - parking
    - payment:credit_cards
    - contact:phone
    - power_supply
    - sanitary_dump_station
campings:
  label:
    fr: Campings
  matches:
    - tourism: camp_site
  osm_tags_extra:
    - wheelchair
    - tents
    - caravans
    - stars
    - operator
    - internet_access
    - wheelchair
    - stars
    - internet_access
    - operator
maisons-de-sante:
  label:
    fr: Maison de santé
  matches:
    - healthcare: centre
      type:FR:FINESS: '603'
  osm_tags_extra:
    - ref:FR:FINESS
    - healthcare:speciality
    - phone
    - contact:phone
    - adress
    - wheelchair
    - website
cliniques:
  label:
    fr: Clinique
  matches:
    - amenity: hospital
      type:FR:FINESS: '365'
  osm_tags_extra:
    - address
medecins-thermaux:
  label:
    fr: Médecins
  matches:
    - amenity: doctors
      healthcare:speciality~general: null
      description~thermal: null
  osm_tags_extra:
    - address
    - phone
    - opening_hours
    - wheelchair
    - description
    - address
    - description
    - healthcare:speciality
    - phone
    - contact:phone
    - website
zones-de-baignades-surveillees-osm:
  label:
    fr: Zone de baignade surveillée
  matches:
    - leisure: swimming_area
      supervised: 'yes'
  osm_tags_extra:
    - lit
    - supervised
    - description
    - water
    - opening_hours
    - description
    - water
    - wheelchair
    - lit
port-de-peche:
  label:
    fr: Port de pêche
  matches:
    - seamark:type: harbour
      seamark:harbour:category: fishing
  osm_tags_extra:
    - wheelchair
    - description
    - description
    - wheelchair
    - produce
port-de-plaisance-osm:
  label:
    fr: Port de plaisance
  matches:
    - leisure: marina
      access!: customers
  osm_tags_extra:
    - wheelchair
    - description
    - description
    - wheelchair
aires-de-vidange-de-camping-car:
  label:
    fr: Aire de vidange de camping-car
  matches:
    - amenity: sanitary_dump_station
  osm_tags_extra:
    - wheelchair
    - description
    - sanitary_dump_station:grey_water
    - sanitary_dump_station:chemical_toilet
    - water_point
    - fee
    - wheelchair
    - fee
    - water_point
    - description
point-wifi:
  label:
    fr: Accès wifi
  matches:
    - internet_access: wlan
      internet_access:fee: 'no'
  osm_tags_extra:
    - internet_access:fee
    - description
    - operator
    - fee
    - internet_access:fee
    - description
    - operator
    - opening_hours
    - address
lavoirs-osm:
  label:
    fr: Lavoir
  matches:
    - amenity: lavoir
  osm_tags_extra:
    - opening_hours
    - fee
    - access
    - shelter
    - tourism
    - historic
    - shelter
    - tourism
    - water
    - wall
musees-nationaux-osm:
  label:
    fr: Musée national
  matches:
    - tourism: museum
      ~^ref:FR:museofile*$~^.: null
  osm_tags_extra:
    - opening_hours
    - fee
    - access
    - description
    - phone
    - contact:phone
    - website
    - opening_hours
    - fee
    - wheelchair
    - contact:email
    - ref:FR:museofile
autres-musees-osm:
  label:
    fr: Autres musées
  matches:
    - tourism: museum
      ref:FR:museofile!~.: null
  osm_tags_extra:
    - opening_hours
    - fee
    - access
    - description
    - phone
    - contact:phone
    - opening_hours
    - website
    - fee
    - wheelchair
    - contact:email
marches-a-lannee:
  label:
    fr: Marché à l'année
  matches:
    - amenity: marketplace
      produce!: fish
  osm_tags_extra:
    - wheelchair
    - address
    - opening_hours
    - description
    - wheelchair
    - organic
    - produced_on_site
marches-aux-poissons:
  label:
    fr: Marché aux poissons
  matches:
    - amenity: marketplace
      produce: fish
  osm_tags_extra:
    - wheelchair
    - opening_hours
villages-vacances-osm:
  label:
    fr: Village vacances
  matches:
    - leisure: resort
  osm_tags_extra:
    - wheelchair
    - stars
    - tourism
    - internet_access
    - washing_machine
    - brand
    - wheelchair
    - stars
    - brand
    - operator
    - swimming_pool
sites-de-visite:
  label:
    fr: CDT40
  matches:
    - name: Comité Départemental du Tourisme des Landes
  osm_tags_extra:
    - phone
    - description
    - address
    - opening_hours
    - wheelchair
    - contact:email
    - contact:website
    - website
    - contact:facebook
    - internet_access
    - phone
    - contact:phone
    - description
    - address
    - opening_hours
    - wheelchair
    - facebook
    - contact:facebook
    - contact:website
    - contact:email
    - internet_access
cinemas:
  label:
    fr: Cinémas
  matches:
    - amenity: cinema
  osm_tags_extra:
    - operator
    - opening_hours
    - phone
    - website
    - address
    - wheelchair
poissonneries:
  label:
    fr: Poissoneries
  matches:
    - shop: seafood
  osm_tags_extra:
    - wheelchair
    - description
    - opening_hours
    - phone
    - contact:phone
    - website
    - contact:facebook
decheteries:
  label:
    fr: Déchèteries
  matches:
    - amenity: recycling
      recycling_type: centre
  osm_tags_extra:
    - recycling_type
    - operator
    - recycling:glass_bottles=yes
    - recycling:plastic_bottles=yes
    - recycling:beverage_carton=yes
    - recycling:cans=yes
    - recycling:paper=yes
    - recycling:clothes=yes
    - recycling:batteries=yes
    - recycling:waste
    - recycling_type
    - operator
    - recycling:glass_bottles=yes
    - recycling:beverage_carton=yes
    - recycling:cans=yes
    - recycling:paper=yes
    - recycling:clothes=yes
    - recycling:batteries=yes
    - recycling:waste
hotels-osm:
  label:
    fr: Hôtels
  matches:
    - tourism: hotel
  osm_tags_extra:
    - wheelchair
    - tents
    - caravans
    - stars
    - operator
    - internet_access
    - ref:FR:CRTA
    - address
    - phone
    - stars
restaurant-osm:
  label:
    fr: Restaurant
  matches:
    - amenity: restaurant
  osm_tags_extra:
    - ref:FR:CRTA
    - address
    - phone
fermes-vivrieres:
  label:
    fr: Fermes vivrières
  matches:
    - landuse: farmyard
      product!: wine
  osm_tags_extra:
    - operator
    - ref:FR:SIRET
    - address
    - phone
    - email
    - website
    - facebook
    - organic
postbox:
  label:
    fr: postbox
  matches:
    - amenity: post_box
      collection_times: null
  osm_tags_extra:
    - description
    - operator
    - wheelchair
    - opening_hours
    - address
    - description
    - operator
    - wheelchair
    - opening_hours
espaces-de-coworking:
  label:
    fr: Espace de coworking
  matches:
    - amenity: coworking_space
  osm_tags_extra:
    - opening_hours
    - phone
    - contact:phone
    - website
    - email
    - contact:facebook
    - facebook
    - address
    - description
    - mobile
    - contact:mobile
facebook:
  label:
    fr: Facebook
  matches:
    - facebook: null
  osm_tags_extra: []
fusion-facebook:
  label:
    fr: Facebook fusion
  matches:
    - facebook: null
    - contact:facebook: null
  osm_tags_extra: []
