services:
  postgres:
    image: postgis/postgis:15-3.4
    shm_size: 1g
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./lib/time_machine/sql/:/scripts
      - projects_config:/projects_config
      - projects_data:/projects_data
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      start_interval: 1s
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  script:
    profiles:
      - tools
    image: ghcr.io/teritorio/clearance-api:${CLEARANCE_VERSION:-dev}
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres@postgres:5432/postgres
      - PUBLIC_URL=${PUBLIC_URL}
      - SENTRY_DSN_TOOLS=${SENTRY_DSN_TOOLS:-}
      - OSM_GEOFABRIK_PASSWORD=${OSM_GEOFABRIK_PASSWORD:-}
      - OSM_GEOFABRIK_USER=${OSM_GEOFABRIK_USER:-}
      - PROJECTS_CONFIG_PATH=/projects_config
      - PROJECTS_DATA_PATH=/projects_data
    volumes:
      - ./lib/time_machine/sql:/sql
      - projects_config:/projects_config
      - projects_data:/projects_data
    depends_on:
      - postgres
    healthcheck:
      disable: true

  api:
    build:
      context: .
    image: ghcr.io/teritorio/clearance-api:${CLEARANCE_VERSION:-dev}
    environment:
      - RAILS_ENV=${RAILS_ENV:-production}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-Toe8eihai5ieShai}
      - OSM_OAUTH2_ID=${OSM_OAUTH2_ID}
      - OSM_OAUTH2_SECRET=${OSM_OAUTH2_SECRET}
      - OSM_OAUTH2_REDIRECT=${OSM_OAUTH2_REDIRECT}
      - DATABASE_URL=postgresql://postgres@postgres:5432/postgres
      - SENTRY_DSN_API=${SENTRY_DSN_API:-}
      - PROJECTS_CONFIG_PATH=/projects_config
      - PROJECTS_DATA_PATH=/projects_data
    volumes:
      - ./lib/time_machine/sql:/sql
      - ./cache:/cache
      - projects_config:/projects_config
      - projects_data:/projects_data
    depends_on:
      - postgres
    command: bundle exec rails server --pid /dev/shm/server.pid --binding=0.0.0.0 --port 9000
    restart: unless-stopped

  frontend:
    build:
      context: frontend
    image: ghcr.io/teritorio/clearance-frontend:${CLEARANCE_VERSION:-develop}
    environment:
      - NUXT_PUBLIC_API=${PUBLIC_URL}/api/0.1
      - NUXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN_FRONTEND:-}
      - NUXT_PUBLIC_SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}
    depends_on:
      - api
    restart: unless-stopped

  reverse-proxy:
    image: nginx
    ports:
      - ${NGINX_PORT:-8000}:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - projects_config:/projects_config
      - projects_data:/projects_data
    depends_on:
      - api
      - frontend
    healthcheck:
      test: service nginx status || exit 1
      start_interval: 1s
      start_period: 30s
      interval: 30s
      timeout: 20s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  projects_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./projects_config
  projects_data:
