services:
  postgres:
    image: postgis/postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./pbf:/pbf
      - pgdata:/var/lib/postgresql/data
#    restart: unless-stopped

  api:
    build:
      context: api
    environment:
      - CONFIG=/srv/app/conf.yaml
      - DATABASE_URL=postgresql://postgres@postgres:5432/postgres
    ports:
      - 9000:9000
    volumes:
      - ./api/time_machine/sql:/sql
      - ./api/:/srv/app/
      - ./conf.yaml:/srv/app/conf.yaml
    depends_on:
      - postgres
    command: bundle exec rails server --binding=0.0.0.0 --port 9000
#    restart: unless-stopped

volumes:
  pgdata:
