version: '3'

services:
  postgres:
    image: postgis/postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./scripts:/scripts
      - ./projects:/projects
      - pgdata:/var/lib/postgresql/data
#    restart: unless-stopped

  api:
    build:
      context: api
    environment:
      - RAILS_ENV=${RAILS_ENV:-production}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-Toe8eihai5ieShai}
      - DATABASE_URL=postgresql://postgres@postgres:5432/postgres
    ports:
      - 9000:9000
    volumes:
      - ./api/time_machine/sql:/sql
      - ./api/:/srv/app/
      - ./projects:/projects
    depends_on:
      - postgres
    command: bundle exec rails server --binding=0.0.0.0 --port 9000
#    restart: unless-stopped

volumes:
  pgdata:
