version: '3'

services:
  postgres:
    image: postgis/postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./lib/time_machine/sql/:/scripts
      - ./projects:/projects
      - pgdata:/var/lib/postgresql/data
#    restart: unless-stopped

  api:
    build:
      context: .
    environment:
      - RAILS_ENV=${RAILS_ENV:-production}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-Toe8eihai5ieShai}
      - OSM_OAUTH2_ID=${OSM_OAUTH2_ID}
      - OSM_OAUTH2_SECRET=${OSM_OAUTH2_SECRET}
      - OSM_OAUTH2_REDIRECT=${OSM_OAUTH2_REDIRECT}
      - DATABASE_URL=postgresql://postgres@postgres:5432/postgres
    ports:
      - 9000:9000
    volumes:
      - ./lib/time_machine/sql:/sql
      - ./:/srv/app/
      - ./cache:/cache
      - ./projects:/projects
    depends_on:
      - postgres
    command: bundle exec rails server --binding=0.0.0.0 --port 9000
#    restart: unless-stopped

  download:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./projects:/projects
#    restart: unless-stopped

volumes:
  pgdata:
