# frozen_string_literal: true

source 'https://rubygems.org'

gem 'json'
gem 'optparse'
gem 'pg'
gem 'sorbet-runtime'

group :development do
  gem 'rake'
  gem 'rubocop', require: false
  gem 'rubocop-rake', require: false
  gem 'ruby-lsp', require: false
  gem 'sorbet'
  gem 'tapioca', require: false
  gem 'test-unit'

  # Only for sorbet typechecker
  gem 'psych'
  gem 'racc'
  gem 'rbi'
  gem 'yard'
end
