name: Test Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: bundle install

      # - name: Run typecheck
      #   run: |
      #     bundle exec tapioca init && \
      #     bundle exec rake rails_rbi:routes && \
      #     bundle exec tapioca dsl && \
      #     bundle exec srb typecheck -q

      - name: Run rubocop
        run: bundle exec rubocop -c ../.rubocop.yml

      - name: Run tests
        run: bundle exec rake test
